// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_vgwKbGGzHuTYdAaeHNpcj7LVgAIDyFY',
    appId: '1:904253282096:web:712deb8a5b42bedc4c1af5',
    messagingSenderId: '904253282096',
    projectId: 'medicalappointment-46925',
    authDomain: 'medicalappointment-46925.firebaseapp.com',
    storageBucket: 'medicalappointment-46925.firebasestorage.app',
    measurementId: 'G-CJPM1DL16M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn4ZimbsUnDWwpJ2odxDe-q9HbSEB4Dg8',
    appId: '1:904253282096:android:3d55ed1a8ec7e2d24c1af5',
    messagingSenderId: '904253282096',
    projectId: 'medicalappointment-46925',
    storageBucket: 'medicalappointment-46925.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl9izgxTvzFn-41e2XmfjcjVGzo2si_Dw',
    appId: '1:904253282096:ios:e7764bba83e4c8e74c1af5',
    messagingSenderId: '904253282096',
    projectId: 'medicalappointment-46925',
    storageBucket: 'medicalappointment-46925.firebasestorage.app',
    iosBundleId: 'com.example.doctorBookingSystemWithAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl9izgxTvzFn-41e2XmfjcjVGzo2si_Dw',
    appId: '1:904253282096:ios:e7764bba83e4c8e74c1af5',
    messagingSenderId: '904253282096',
    projectId: 'medicalappointment-46925',
    storageBucket: 'medicalappointment-46925.firebasestorage.app',
    iosBundleId: 'com.example.doctorBookingSystemWithAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_vgwKbGGzHuTYdAaeHNpcj7LVgAIDyFY',
    appId: '1:904253282096:web:9a1a5cc6dd0188664c1af5',
    messagingSenderId: '904253282096',
    projectId: 'medicalappointment-46925',
    authDomain: 'medicalappointment-46925.firebaseapp.com',
    storageBucket: 'medicalappointment-46925.firebasestorage.app',
    measurementId: 'G-Y7QYN98HJ8',
  );
}
